site_name: LaTeX Tutorial
site_url: https://bibaijin.github.io/tutorial-LaTeX
site_description: LaTeX 的学习心得
site_author: bibaijin

repo_url: https://github.com/bibaijin/tutorial-LaTeX

theme: mkdocs
theme_dir: 'custom_theme'

pages:
- 首页: index.md
- LaTeX: LaTeX.md
- 关于: about.md

markdown_extensions:
    - smarty
    - sane_lists
    - footnotes
    - tables

copyright: Copyright &copy; 2015 <a href="mailto:bibaijin@gmail.com">金比白</a>.
